git-proxy:
  auto-clean-strategy:
    zip-file:
      time: 1
      unit: hours
    temp-dir:
      time: 10
      unit: seconds

spring:
  output:
    ansi:
      enabled: detect

logging:
  level:
    com.nancheung.gitproxy.task: debug