git-proxy:
  auto-clean-strategy:
    zip-file:
      time: 10
      unit: seconds
    temp-dir:
      time: 10
      unit: seconds

spring:
  # json配置
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: detect
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/git_proxy
    username: root
    password: GitProxyYes!

mybatis-plus:
  global-config:
    banner: false

logging:
  level:
    com.nancheung.gitproxy: debug