git-proxy:
  auto-clean-strategy:
    zip-file:
      time: 10
      unit: seconds
    temp-dir:
      time: 10
      unit: seconds

spring:
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: detect

logging:
  level:
    com.nancheung.gitproxy: debug