git-proxy:
  auto-clean-strategy:
    zip-file:
      time: 10
      unit: seconds
    temp-dir:
      time: 10
      unit: seconds

spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/git_proxy
    username: root
    password: GitProxyYes!

logging:
  level:
    root: error

swagger:
  enabled: false